### ISSUE TITLE
About the sprite

### ISSUE THREAD

**Issue by EzequielAdrianM** [jsramraj/flags#4]
May i ask why the sprite is wasting a lot of empty space? All the flags could be put together, to make a smaller and lighter file..

**Comment by EzequielAdrianM** [comment]
Oh, i understand. The pictures are ordered in a matrix from AA to ZZ according to **ISO 3166-1 alpha-2 codes** .. anyways, i pased the sprite file through an image compressor called tinypng.com and reduced the sprite size in 64%. From 93kb to 34kb.

**Comment by jsramraj** [comment]
Yeah. Checkout my other tool https://github.com/jsramraj/flag-sprite-creator. If you want bigger icon/higher resolution images, want more/less padding, you can do that by creating and feeding your own new sprite image.
